### ISSUE TITLE
ユーザーのマイページを整える

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager-2#119]
# 開発目的

現在登録できるものをマイページで表示できるようにする

# 考えられる開発内容

マイページをかなり編集する

# 考えられる開発時間

2日

# 備考

**Comment by kugue99A** [comment]
なんか新規登録できない
![image](https://user-images.githubusercontent.com/66663224/100428345-26ae6f80-30d7-11eb-867e-84634771f43a.png)

**Comment by kugue99A** [comment]
ログインもできなかった
![Uploading image.png…]()

**Comment by oba18** [comment]
多分，コマンドが足りてないかもね

**Comment by oba18** [comment]
`docker-compose run --rm api rails db:migrate:reset`
`docker-compose run --rm api rails db:seed_fu`
