### ISSUE TITLE
ステージオプションのvalidationの作成

### ISSUE THREAD

**Issue by ryuseifujisaki** [NUTFes/group-manager-2#1190]
# 開発目的

準備、企画、片付けの設定時間の合計を120分以下のvalidationを設定する

# 考えられる開発内容

# 考えられる開発時間

# 備考

**Comment by TsubasaOura** [comment]
参考になりそう？
https://scrapbox.io/teamlab-frontend/VeeValidate%E3%81%A7%E4%BB%96%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E5%80%A4%E3%82%82%E5%90%AB%E3%82%81%E3%81%A6%E3%83%90%E3%83%AA%E3%83%87%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95

**Comment by TsubasaOura** [comment]
https://qiita.com/someone7140/items/f453335db90e9871e6ec
