### ISSUE TITLE
stageの希望場所のバリデーションを行う

### ISSUE THREAD

**Issue by ryuseifujisaki** [NUTFes/group-manager-2#1210]
# 開発目的

現状同じ会場を登録できるのでバリデーションをかける。
可能なら、希望なしが二つの場合は登録できるようにする
![image](https://github.com/NUTFes/group-manager-2/assets/50622120/7409a43d-e0e9-4a8e-a53d-ac094d3a528d)

# 考えられる開発内容

# 考えられる開発時間

# 備考

**Comment by TsubasaOura** [comment]
paswordとconfirmPasswordのvalidation参考にすればできそう
