### ISSUE TITLE
物品申請のカテゴリーによる選択肢の絞り込みの確認

### ISSUE THREAD

**Issue by harata-t** [NUTFes/group-manager-2#1540]
# 開発目的

- カテゴリーによって申請できる貸出物品が違うので、カテゴリーごとに選択できる物品を確認する
- 個数のバリデーションがかかっているか確認する

- 食品販売
    - 机(最大20個)
    - 椅子(最大20個)
    - 長机
    - パーテーション
    - 掲示板
    - テント(1棟)
- ステージ団体
    - 机
    - 椅子
    - 長机
- 物品販売、展示・体験、研究室、実行委員、その他
    - 屋内
        - 机
        - 椅子
        - パーテーション
        - 掲示板
    - 屋外
        - 机(最大20個)
        - 椅子(最大20個)
        - 長机
        - パーテーション
        - 掲示板
        - テント(1棟)

# 考えられる開発内容

# 考えられる開発時間

# 備考

**Comment by nose221834** [comment]
実行委員と食品販売のバリデーションはでけた

残りステージとその他

**Comment by nose221834** [comment]
テントは小も大も選べるようにする
ただ、どちらか一方のみ、かつ一つまで

**Comment by nose221834** [comment]
追加する際の、場所ごとの貸し出し物品のバリデーションはできるようになった

**Comment by nose221834** [comment]
残りのダスク

- 追加されたタスクの修正cardにバリデーションをつける
- 追加するカードの数のバリデーションをつける

**Comment by nose221834** [comment]
追加するカードの数のバリデーションをつける
を達成

**Comment by nose221834** [comment]
memo
パーティーション足を無くして、パーティーションを登録したら勝手に登録されるようにする

**Comment by nose221834** [comment]
屋内なのか屋外なのかわかんないのきもくないか？？？

**Comment by nose221834** [comment]
「屋内物品と屋外物品が混在しています。統一してください。」エラーを出す。

**Comment by nose221834** [comment]
できなかったので、選んでもらえるように文章かいた。
