### ISSUE TITLE
ステージ申請のバリデーション確認

### ISSUE THREAD

**Issue by harata-t** [NUTFes/group-manager-2#1542]
# 開発目的

- 天候による選択できるステージが変わっているか確認する
- 晴天
    - メインステージ（屋外）
    - 体育館（屋内）
    - 武道館（屋内）
- 雨天
    - 体育館（屋内）
    - 武道館（屋内）

# 考えられる開発内容

# 考えられる開発時間

# 備考

**Comment by KazumaSun** [comment]
以下の動作を確認しました。
編集が必要なら教えてください

晴天時
- メインステージ
- サブステージ
- 体育館
- マルチメディアセンター
- 武道館

雨天時
- 体育館
- マルチメディアセンター
- 武道館
