### ISSUE TITLE
ユーザー詳細からメールを送るようにする

### ISSUE THREAD

**Issue by mashita1023** [NUTFes/group-manager-2#479]
# 開発目的

# 考えられる開発内容

nutfes.shikobuから内容と題名を入力したら送れるようにする
妥協でmail_toでできる
# 考えられる開発時間

# 備考

**Comment by oba18** [comment]
妥協案：to_mail
ちゃんと案：管理者画面でモーダルを出して，そこから自動でメールを飛ばす
RubyでGmailのGemを使う
