### ISSUE TITLE
ログインしてない状態でマイページに飛ばないよう修正

### ISSUE THREAD

**Issue by mashita1023** [NUTFes/group-manager-2#493]
# 開発目的

ログインしていない状態で技大祭のアイコンを押すとマイページに飛んでしまうため、飛んでもマイページに遷移するかそもそもマイページに遷移しないように修正する
# 考えられる開発内容

管理者などのページに直リンク対策があるはずなのでそちらを参考
# 考えられる開発時間

# 備考

**Comment by oba18** [comment]
これをnuxt.config.jsに追記
```
  router: {
    middleware: ['auth']
  }
```

signupはログインしなくてもアクセスできるようにしたいので，これを追記
```
<script>
export default {
  auth: false,
}
</script>
```
