### ISSUE TITLE
管理者画面の諸々修正

### ISSUE THREAD

**Issue by oba18** [NUTFes/group-manager-2#602]
# 開発目的

- 表示が変になっているところを直す
- 新しくできたAPIの形に合わせるようにして修正する

# 考えられる開発内容

# 考えられる開発時間

# 備考

**Comment by kugue99A** [comment]
やることリスト

- [x] グローバルスタイルを作る
- [x] Cardコンポーネントを作る
- [x] Rowコンポーネントを作る
- [ ] Colコンポーネントを作る
- [x] default.vueの修正
- [x] Header.vueの修正
- [x] Menu.vueの修正
