### ISSUE TITLE
リリース22.02 デプロイ

### ISSUE THREAD

**Issue by TsubasaOura** [NUTFes/group-manager-2#723]
# 開発目的

リリース20.02のデプロイ

# 考えられる開発内容

- api/config/database.yml
- nginx/nginx.conf

# 考えられる開発時間

# 備考

**Comment by TsubasaOura** [comment]
/view/vue-project/dist
が.gitignoreで無視されてるはずなのに無視されてなかったので対処しました

**Comment by oba18** [comment]
@TsubasaOura 
new pull requestでプルリク作り直そう
